### ISSUE TITLE
Phase 1 Tracking

### ISSUE THREAD

**Issue by hugomrdias** [ipfs-examples/example-template#1]
# Tracking for  Phase 1 Multirepo-ization

- [ ] Setup CI to pull from remote source repos
- [ ] Add all the js-ipfs examples
- [ ] Proper setup for the ipfs-examples organisation (ask andy)
- [ ] Turn off issue/wikis/projects/discussions for all examples
- [ ] Add descriptions in each repo
- [ ] Add website pointing back to the original source 
- [ ] Disable Releases/Environments/Packages in each repo 
<img width="1161" alt="Screenshot 2021-06-10 at 10 31 54" src="https://user-images.githubusercontent.com/314190/121501368-160c7980-c9d7-11eb-9fb5-513464a60d0b.png">

**Comment by hugomrdias** [comment]
@autonome please review

**Comment by hugomrdias** [comment]
The current CI setup runs every 5 minutes which can be a little heavy what would be an acceptable time frame for this @autonome ?

**Comment by autonome** [comment]
>  Add website pointing back to the original source

what is this part?


> The current CI setup runs every 5 minutes which can be a little heavy what would be an acceptable time frame for this 

daily is probably more than often enough

possibly could even only do on releases of core libs?

**Comment by hugomrdias** [comment]
> > Add website pointing back to the original source
> 
> what is this part?

<img width="1121" alt="Screenshot 2021-06-10 at 15 01 33" src="https://user-images.githubusercontent.com/314190/121538662-dd7f9680-c9fc-11eb-886f-03b5837af61a.png">

Which URL would you like here [issues](https://github.com/ipfs/js-ipfs/issues), [example original folder](https://github.com/ipfs/js-ipfs/tree/master/examples/ipfs-101) or other ?

> 
> > The current CI setup runs every 5 minutes which can be a little heavy what would be an acceptable time frame for this
> 
> daily is probably more than often enough
> 
> possibly could even only do on releases of core libs?

Changed the cron schedule to "at the end of every day" https://github.com/ipfs-examples/example-template/blob/master/.github/workflows/main.yml#L5

Custom triggers coming from releases are more complex because the original repo would need to keep track of all example repos and send POST request for each one. Maybe we can come back to this later?

**Comment by hugomrdias** [comment]
What about `ipfs-examples` org profile ?
 
<img width="764" alt="Screenshot 2021-06-10 at 15 16 50" src="https://user-images.githubusercontent.com/314190/121541357-220c3180-c9ff-11eb-8f76-a31552a351a3.png">

Any guidance in what to put on here?

**Comment by autonome** [comment]
> Which URL would you like here [issues](https://github.com/ipfs/js-ipfs/issues), [example original folder](https://github.com/ipfs/js-ipfs/tree/master/examples/ipfs-101) or other ?

js-ipfs issues

> Custom triggers coming from releases are more complex because the original repo would need to keep track of all example repos and send POST request for each one. Maybe we can come back to this later?

Definitely not a requirement, probably over-optimizing there anyway 😁

**Comment by autonome** [comment]
> What about `ipfs-examples` org profile ?
> Any guidance in what to put on here?

Anything public should do contact@

Anything related to billing/admin should use whatever ipfs org uses (maybe ask Andy if you can't tell)

**Comment by oliveriosousa** [comment]
Hi @autonome, 

Make sense to have a prefix for the examples? 

For now, we are currently working only on the ipfs-js examples but ipfs has other repositories that may have the same example structure (for instance, go-ipfs).

e.g.: js-ipfs-{example-name}, go-ipfs-{example-name} ...

**Comment by autonome** [comment]
That sounds great to help make clear which language 👍🏼👍🏼👍🏼
