### ISSUE TITLE
Phase 2 Tracking

### ISSUE THREAD

**Issue by oliveriosousa** [ipfs-examples/example-template#3]
# Tracking for Phase 2: Improve ergonomics

- [ ] Update existing examples to be more concise (readme's, content itself, versions, etc)
- Create template for new examples
- Plan what should be mandatory to implement (core functionality)
- Perform bump version automatically
- [ ] Add more examples 
- Web Frameworks/Libraries: svelte, angular
- Bundlers: Vite, Rollup, snowpack
- Deno

**Comment by oliveriosousa** [comment]
Hi team,

1. I noticed that a lot of commits in the examples are related with update the version of IPFS. It is possible to add `tags` to IPFS release? Or just target the latest release.

> For example:
> Stable, Beta, Next, Preview

2. What should be the core for all examples ? (MFS API ?)
3. Suggestions for more examples 😃

**Comment by hugomrdias** [comment]
> Hi team, @autonome @hugomrdias
> 
> 1. I noticed that a lot of commits in the examples are updates to the version of IPFS. It is possible to add `tags` to IPFS release? Or just target the latest release?

I don't see this has a problem, its just keeping the same history as the source.

> 1. What should be the core for all examples ? (MFS API ?)

For new examples that focus only on new frameworks and bundlers it should just be similar to `ipfs-101` i.e. `ipfs.version()`, `ipfs.id()`, `ipfs.add(cid)` and `ipfs.cat(cid)`


> Perform bump version automatically

What do you mean by this ? We dont need versions in the examples.

The first task for phase 2 should be just, go through each example and make sure it's as easy as it can be.
- Check if it actually works properly 
- Check if dependencies need to be updated
- Check if the code can be made simpler
- Check if the tooling (npm script, bundler configs, etc) can be made simpler


All of these should be made as PRs in the js-ipfs repo.
Updating the readme and making the examples look better should be done in Phase 4.

The second tasks looks good, if for some reason you can't make js-ipfs work with some new framework or bundler an issue should be created explaining why so the devs can look into it.

**Comment by hugomrdias** [comment]
@oliveriosousa after talking with @autonome and @achingbrain we feel that the examples should be extracted from the js-ipfs monorepo and recreated in this org

The high level task should be:
- [ ] Create ipfs-examples/js-ipfs-examples repo
- [ ] Copy all the examples in js-ipfs to the above repo
- [ ] The new repo should be a mono-repo using node 16, npm 7 workspaces 
- [ ] Each example should have tests using https://playwright.dev/docs/test-intro and the `npm test` script should run everything needed
- [ ] The standalone repos should be updated to pull from this new mono-repo instead of js-ipfs repo
- [ ] js-ipfs repo should be able to run tests for each example using the external testing setup that is already used for partners repos


@achingbrain
The PRs already opened in the js-ipfs should be ported over or can we merge them before creating the new examples mono.repo ?

**Comment by achingbrain** [comment]
> The PRs already opened in the js-ipfs should be ported over or can we merge them before creating the new examples mono.repo ?

I think it would be less disruptive it they go straight into the new examples monorepo.

**Comment by oliveriosousa** [comment]
## Current issues: 

### 1. IPNS

#### Issue description

When publishing a IPFS hash it is being thrown an error running the following code:

https://github.com/ipfs-examples/js-ipfs-examples/blob/120d2638f3a14ee56370e35aea09ac35acb1a5f1/examples/browser-ipns-publish/src/index.js#L209

#### Steps to reproduce the issue

1. Install and run the example: 
  - npm install
  - npm start
2. Create and init an IPFS node (I used IPFS desktop)
3. Add new address to handle WS connections
4. In the browser (see image below)
  - Connect with the API
  - Connect via Websocket
  - IPFS Hash

#### What's the expected result?

- Being able to publish an IPFS Hash to IPNS

#### What's the actual result?

- See image below

#### Additional details / screenshot

![Screenshot 2021-07-22 at 13 04 03](https://user-images.githubusercontent.com/47525443/126636324-71365b5c-b6e5-4eaa-a467-a13e9f188610.png)




### 2. Service Worker

#### Issue description

Not able to run correctly the example, simply just can't replicate the expected behaviour 

#### Steps to reproduce the issue

1. Install and run the example: 
  - npm install
  - npm start
2. Perform all the steps described in the Readme file

#### What's the expected result?

- Being able to see IPFS content locally using the URL

#### What's the actual result?

- It is being displayed always the homepage

#### Additional details / screenshot

- N/A
